### ISSUE TITLE
clicking on tab shows nothing

### ISSUE THREAD

**Issue by kzkpro** [Smile-SA/magento2-module-seller#16]
hi, does this module works? i've installed it but clicking on simle tab do nothing screenshot attached. 
![chrome-capture](https://user-images.githubusercontent.com/854300/57205548-16a7da00-6fdf-11e9-89c3-4477769db4d8.gif)

Thanks!

**Comment by Fdec** [comment]
Hi @kzkpro 

This module works fine. Have you got an error on your console ?

**Comment by Fdec** [comment]
This module works fine and you give me no response, so I close this issue.
You can open a new issue if you have a new bug.
