### ISSUE TITLE
Entity type id collision

### ISSUE THREAD

**Issue by Vedrillan** [Smile-SA/magento2-module-seller#4]
Magento use hardcoded entity type id, check magento/module-catalog/Setup/CategorySetup.php in getDefaultEntities(). As a result on a fresh install if the setup of smile-seller is executed before the Magento ones (which is my case), the first increments of entity_type_id might already be taken resulting in an "Integrity constraint violation" during the insert of other Magento entity type.

**Comment by Vedrillan** [comment]
This issue happened on branch 1.2.x

**Comment by romainruaud** [comment]
Fixed in 1.2.x

Feel free to reopen if needed.
